language: node_js
node_js:
  - "node"

cache: npm

script: npm run travis-build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: dev
  target_branch: master
